# -*- coding: utf-8 -*-


project   = "benry-config"
release   = ENV['RELEASE'] || "0.0.0"
copyright = "copyright(c) 2016 kuwata-lab.com all rights reserved"
license   = "MIT License"

target_files = Dir[*%W[
  README.md MIT-LICENSE.txt Rakefile
  lib/**/*.rb
  test/**/*_test.rb
  #{project}.gemspec
]]


task :default => :help


desc "show help"
task :help do
  puts "rake help                   # help"
  puts "rake test                   # run test"
  puts "rake package RELEASE=X.X.X  # create gem file"
  puts "rake publish RELEASE=X.X.X  # upload gem file"
end


desc "do test"
task :test do
  sh "ruby", *Dir.glob("test/*.rb")
end


desc "create package"
task :package do
  release != "0.0.0"  or
    raise "specify $RELEASE"
  ## copy
  dir = "build"
  rm_rf dir if File.exist?(dir)
  mkdir dir
  target_files.each do |file|
    dest = File.join(dir, File.dirname(file))
    mkdir_p dest, :verbose=>false unless File.exist?(dest)
    cp file, "#{dir}/#{file}"
  end
  ## edit
  Dir.glob("#{dir}/**/*").each do |file|
    next unless File.file?(file)
    File.open(file, 'rb+') do |f|
      s = f.read()
      s = s.gsub(/\$Release:.*?\$/,   "$"+"Release: #{release} $")
      s = s.gsub(/\$Copyright:.*?\$/, "$"+"Copyright: #{copyright} $")
      s = s.gsub(/\$License:.*?\$/,   "$"+"License: #{license} $")
      #
      f.rewind()
      f.truncate(0)
      f.write(s)
    end
  end
  ## build
  chdir dir do
    sh "gem build #{project}.gemspec"
  end
  mv "#{dir}/#{project}-#{release}.gem", "."
end


desc "upload gem file to rubygems.org"
task :publish do
  release != "0.0.0"  or
    raise "specify $RELEASE"
  #
  gemfile = "#{project}-#{release}.gem"
  print "** Are you sure to publish #{gemfile}? [y/N]: "
  ans = $stdin.gets().strip()
  if ans.downcase.start_with?("y")
    sh "gem push #{gemfile}"
    sh "git tag #{project}-#{release}"
    sh "git push --tags"
  end
end
